#!/usr/bin/env bash
set -Eeuo pipefail

help() {
	cat <<'EOF'
Usage: bash install/install.sh <bash|zsh>

Install the selected shell's rc file in HOME. An existing rc file is moved to
a unique private backup directory in HOME. Reapplying identical content is a no-op.
EOF
}

die() {
	printf 'Error: %s\n' "$1" >&2
	return 1
}

write_rc() {
	local candidate=$1
	local init_path=$2
	printf '# Generated by shelld. Edit the repository settings instead.\n' >"$candidate"
	printf 'this_shelld_path=%q\n' "$init_path" >>"$candidate"
	cat >>"$candidate" <<'EOF'
if [ -r "$this_shelld_path" ]; then
	source "$this_shelld_path"
else
	printf 'Cannot read shell settings: %s\n' "$this_shelld_path" >&2
fi
unset this_shelld_path
EOF
}

install_rc() {
	local target=$1
	local script_dir repo_dir rc candidate backup_dir cleanup
	script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
	repo_dir=$(dirname "$script_dir")
	rc="$HOME/.${target}rc"
	[[ -d $HOME && -w $HOME ]] || {
		die "HOME is not a writable directory: $HOME"
		return 1
	}

	candidate=$(mktemp "$HOME/.${target}rc.shelld-new.XXXXXXXX") || return 1
	printf -v cleanup 'rm -f %q' "$candidate"
	trap "$cleanup" EXIT
	write_rc "$candidate" "$repo_dir/init.sh"
	if [[ -e $rc || -L $rc ]]; then
		if cmp -s "$candidate" "$rc"; then
			printf '%s already contains the current shelld settings.\n' "$rc"
			return 0
		fi
		backup_dir=$(mktemp -d "$HOME/.shelld-backup.XXXXXXXX") || return 1
		mv "$rc" "$backup_dir/${rc##*/}" || return 1
		printf 'Previous rc saved at %s\n' "$backup_dir/${rc##*/}"
	fi
	if ! mv "$candidate" "$rc"; then
		if [[ -n ${backup_dir:-} ]]; then
			if ! mv "$backup_dir/${rc##*/}" "$rc"; then
				printf 'Error: Could not restore %s. Previous rc remains at %s; restore it after fixing the filesystem error.\n' \
					"$rc" "$backup_dir/${rc##*/}" >&2
			fi
		fi
		die "Could not install $rc."
		return 1
	fi
	printf 'Installed %s. Open a new %s session to load it.\n' "$rc" "$target"
}

main() {
	if [[ ${1:-} == --help || ${1:-} == -h ]]; then
		help
		return 0
	fi
	if [[ $# -ne 1 || ( $1 != bash && $1 != zsh ) ]]; then
		help >&2
		return 2
	fi
	install_rc "$1"
}

main "$@"
